![Imgur](https://i.imgur.com/h4PPC71.png)
#11-modul. Maʼlumotlarga ishlov berish. Maʼlumotlarni tayyorlash
# 11.28. Modul boʻyicha yakuniy amaliy vazifa

**Bu vazifalarni bajargach, maʼlumotlarni yuklash, tozalash, oʻzgartirish, matnlarni normalizatsiya qilish, qiymatlarni tekshirish, guruhlash va tahlil qilish kabi maʼlumotlarga ishlov berish (data processing) koʻnikmalarini egallaysiz.**

#**Umumiy maʼlumotlar bilan ishlash**

#Dataset haqida qisqacha maʼlumot
Restoran savdosi boʻyicha maʼlumotlar toʻplami 17 534 tranzaksiya uchun maʼlumotlarni oʻz ichiga oladi. Maʼlumotlar yetishmayotgan yoki baʼzilari toʻliq kiritilmagan boʻlishi mumkin. Maʼlumotlar toʻplamida asosiy taomlar, shirinliklar, ichimliklar kabi bir nechta toifadagi savdo tafsilotlari mavjud.


 0.   **Unnamed 0** – indekslarni;
 1.   **Order ID** – buyurtma IDʼsini;
 2.   **Customer ID** – mijoz IDʼsini;
 3.   **Category** – mahsulotlar kategoriyasini;
 4.   **Item** – mahsulot nomini;
 5.   **Price** – mahsulotning narxini;
 6.   **Quantity** – qancha mahsulot sotilgani miqdorini;
 7.   **Order Total** – umumiy narx qancha ekanini;
 8.   **Order Date** – buyurtma berilgan sanani (vaqt);
 9.   **Payment Method** – toʻlov usuli turini saqlaydi.

#1) Quyida berilgan datasetni yuklab olib, ustun nomlarini koʻring va ularni maʼno jihatdan tushunarli shaklga keltiring. `Unnamed: 0` ustunini tashlab yuboring!

In [85]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/restaurant_sales.csv"
df = pd.read_csv(url)
df.head()

,Unnamed: 0,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,0,ORD_705844,CUST_092,NaN,side salad#?,3.0,1.0,3.0,2023-12-21,Credit Card
1,1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,3,ORD_630508,CUST_075,Drinks,NaN,-1.0,2.0,5.0,2022-08-09,Credit Card
4,4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

In [132]:
#javobni shu yerda yozing
df = df.drop(columns=['Unnamed: 0'])

In [86]:
df.rename(columns={'Order ID': 'OrderID', 'Customer ID': 'CustomerID', 'Order Total': 'TotalPrice', 'Order Date': 'Date', 'Payment Method':'PaymentMethod'}, inplace=True)
df.head()

,Unnamed: 0,OrderID,CustomerID,Category,Item,Price,Quantity,TotalPrice,Date,PaymentMethod
0,0,ORD_705844,CUST_092,NaN,side salad#?,3.0,1.0,3.0,2023-12-21,Credit Card
1,1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,3,ORD_630508,CUST_075,Drinks,NaN,-1.0,2.0,5.0,2022-08-09,Credit Card
4,4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

#2) Maʼlumotlarning umumiy holatini (info(), describe()) tekshiring.

In [62]:
#javobni shu yerda yozing
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        17534 non-null  object
 1   CustomerID     17534 non-null  object
 2   Category       17498 non-null  object
 3   Item           15776 non-null  object
 4   Price          17534 non-null  float64
 5   Quantity       17104 non-null  float64
 6   TotalPrice     17104 non-null  float64
 7   Date           17534 non-null  object
 8   PaymentMethod  16452 non-null  object
dtypes: float64(3), object(6)
memory usage: 1.2+ MB

In [63]:
df.describe()

              Price      Quantity    TotalPrice
count  17534.000000  17104.000000  17104.000000
mean       6.207312      3.014149     19.914494
std        4.993782      1.414598     18.732549
min       -1.000000      1.000000      1.000000
25%        3.000000      2.000000      7.500000
50%        5.000000      3.000000     15.000000
75%        7.000000      4.000000     25.000000
max       20.000000      5.000000    100.000000

#3) Har bir ustundagi boʻsh qiymatlarni aniqlang va ularni toʻldirish strategiyasini ishlab chiqing.

In [87]:
#javobni shu yerda yozing
df.isnull().sum()

Unnamed: 0          0
OrderID             0
CustomerID          0
Category           36
Item             1758
Price               0
Quantity          430
TotalPrice        430
Date                0
PaymentMethod    1082
dtype: int64

In [89]:
# Item nomini ortiqcha belgilardan tozalash va ilk harflarini katta ko'rinishga keltirish
df['Item'] = df["Item"].str.extract("([a-zA-Z\s]+)", expand=False).str.strip().str.title()
df['Item']

0             Side Salad
1        Mashed Potatoes
2        Grilled Chicken
3                    NaN
4          Pasta Alfredo
              ...
17529                NaN
17530          Ice Cream
17531          Ice Cream
17532    Mashed Potatoes
17533                NaN
Name: Item, Length: 17534, dtype: object

In [90]:
# categoriyani Itemga ko'ra aniqlash
item_category_map = (df.dropna(subset=['Item', 'Category']).drop_duplicates('Item').set_index('Item')['Category'].to_dict())
item_category_map

{'Mashed Potatoes': 'Side Dishes',
 'Grilled Chicken': 'Main Dishes',
 'Pasta Alfredo': 'Main Dishes',
 'Salmon': 'Main Dishes',
 'Garlic Bread': 'Side Dishes',
 'Vegetarian Platter': 'Main Dishes',
 'Brownie': 'Desserts',
 'Sweet Potato Fries': 'Starters',
 'Lemonade': 'Drinks',
 'Side Salad': 'Side Dishes',
 'Orange Juice': 'Drinks',
 'Chocolate Cake': 'Desserts',
 'Coca Cola': 'Drinks',
 'Grilled Vegetables': 'Side Dishes',
 'Cheese Fries': 'Starters',
 'Beef Chili': 'Starters',
 'Chicken Melt': 'Starters',
 'Fruit Salad': 'Desserts',
 'French Fries': 'Starters',
 'Ice Cream': 'Desserts',
 'Cheesecake': 'Desserts',
 'Iced Tea': 'Drinks',
 'Water': 'Drinks',
 'Nachos Grande': 'Starters',
 'Onion Rings': 'Side Dishes',
 'Steak': 'Main Dishes'}

In [91]:
df['Category'] = df.apply(lambda row: item_category_map.get(row['Item'], row['Category']), axis=1)
print(df['Category'].isna().sum())

4

,Unnamed: 0,OrderID,CustomerID,Category,Item,Price,Quantity,TotalPrice,Date,PaymentMethod
3000,3000,ORD_528695,CUST_068,NaN,NaN,-1.0,NaN,NaN,2022-05-01,NaN
10500,10500,ORD_402838,CUST_023,NaN,NaN,-1.0,NaN,NaN,2022-01-20,Cash
15500,15500,ORD_810133,CUST_025,NaN,NaN,-1.0,NaN,NaN,2022-09-30,NaN
17000,17000,ORD_666259,CUST_013,NaN,NaN,-1.0,5.0,25.0,2022-10-04,NaN

In [92]:
# qolga 4 ta Category nanlari qatorini o'chirib yuborish
df.drop(df[df['Category'].isna()].index, inplace=True)

In [121]:
# Quantity nanlrini TotalPrice ni Price ga bo'lish va yana nan qolgan taqdirda min qiymat bilan to'ldirish
df['Quantity'] = df['Quantity'].fillna(df['TotalPrice'] / df['Price'])
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].min())

# TotalPrice da price va Quantity ni ko'paytirish orqali to'ldirish
df['TotalPrice'] = df['TotalPrice'].fillna(df['Price'] * df['Quantity']).abs()

# PaymentMethod nanlarini eng ko'p uchraydigan turi  bilan to'ldirish
df['PaymentMethod'] = df['PaymentMethod'].fillna(df['PaymentMethod'].mode().iloc[0])

In [106]:
# Item ni kategoriyaga ko'ra aniqlash
category_item_map = (df.dropna(subset=['Category', 'Item']).groupby('Category')['Item'].agg(lambda x: x.mode()[0] if not x.mode().empty else 'Unknown').to_dict())
category_item_map

{'Desserts': 'Ice Cream',
 'Drinks': 'Water',
 'Main Dishes': 'Pasta Alfredo',
 'Side Dishes': 'Side Salad',
 'Starters': 'French Fries'}

In [107]:
# nan kategoriyalarni item categoriyasiga ko'ra to'ldirish
df['Item'] = df['Item'].fillna(df['Category'].map(category_item_map))

In [123]:
# manfiy Price va TotalPrice larni musbatga o'zgartirish
df.loc[df['Price'] < 0, 'Price'] = df['Price'].abs()
df.loc[df['TotalPrice'] < 0, 'TotalPrice'] = df['TotalPrice'].abs()

In [129]:
# narxni TotalPrice ga ko'ra hisoblash
df['Price'] = df['TotalPrice']/df['Quantity']

In [135]:
df.isnull().sum()

OrderID          0
CustomerID       0
Category         0
Item             0
Price            0
Quantity         0
TotalPrice       0
Date             0
PaymentMethod    0
dtype: int64

#4) Har bir ustundagi takroriy qiymatlarni toping va ularga qanday oʻzgartirish kiritish kerakligini hal qiling.

In [144]:
#javobni shu yerda yozing

# takroriy qatorlar topilmadi
sum(df.duplicated())

0

#5) Maʼlumotlar toʻplamidagi noto‘g‘ri maʼlumotlar (masalan, son turishi kerak bo‘lgan ustunda matn bo‘lsa) mavjudligini tekshiring va to‘g‘rilang.

In [145]:
#javobni shu yerda yozing
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17530 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        17530 non-null  object
 1   CustomerID     17530 non-null  object
 2   Category       17530 non-null  object
 3   Item           17530 non-null  object
 4   Price          17530 non-null  float64
 5   Quantity       17530 non-null  float64
 6   TotalPrice     17530 non-null  float64
 7   Date           17530 non-null  datetime64[ns]
 8   PaymentMethod  17530 non-null  object
dtypes: datetime64[ns](1), float64(3), object(5)
memory usage: 1.8+ MB

#6) Maʼlumotlar toʻplamidagi **katta/kichik harf** muammolari boʻlgan joylarni toping va bir xil formatga keltiring.

In [16]:
#javobni shu yerda yozing
df['Item'] = df["Item"].str.title()

#7) Maʼlumotlar turini oʻzgartirish.
 * Ustunlarning maʼlumot turlarini tekshiring. Notoʻgʻri turlarga ega boʻlgan ustunlarni toʻgʻri formatga oʻtkazing.
 * `order_date` yoki unga oʻxshash ustunni datetime formatiga oʻtkazing.

In [141]:
#javobni shu yerda yozing
df['Date'] = pd.to_datetime(df['Date'], format="%Y-%m-%d")

#8) Mahsulot nomlarida noto‘g‘ri yoki nomaʼlum belgilar (?, NaN, #) mavjudligini tekshiring va ularni tuzating.

In [18]:
#javobni shu yerda yozing
df['Item'] = df["Item"].str.extract("([a-zA-Z\s]+)", expand=False).str.strip().str.title()
category_item_map = (df.dropna(subset=['Category', 'Item']).groupby('Category')['Item'].agg(lambda x: x.mode()[0] if not x.mode().empty else 'Unknown').to_dict())
df['Item'] = df['Item'].fillna(df['Category'].map(category_item_map))

#**Maʼlumotlarni filtrlash va qayta ishlash**

#9) Manfiy narx yoki 0 ga teng narx qiymatlarini toping va ularni qanday oʻzgartirish kerakligini hal qiling.

In [19]:
#javobni shu yerda yozing
df.loc[df['Price'] < 0, 'Price']
df.loc[df['Price'] < 0, 'Price'] = df['Price'].abs()

df.loc[df['TotalPrice'] < 0, 'TotalPrice']
df.loc[df['TotalPrice'] < 0, 'TotalPrice'] = df['TotalPrice'].abs()

In [148]:
print(df.loc[df['Price'] <= 0, 'Price'])
print(df.loc[df['TotalPrice'] <= 0, 'TotalPrice'])

Series([], Name: Price, dtype: float64)
Series([], Name: TotalPrice, dtype: float64)

#10) Boʻsh toifalar (kategoriya) mavjudligini tekshiring va toʻgʻri kategoriya berish strategiyasini ishlab chiqing.

In [149]:
#javobni shu yerda yozing
print(df['Category'].isna().sum())

0

In [ ]:
# categoriyani Itemga ko'ra aniqlash
item_category_map = (df.dropna(subset=['Item', 'Category']).drop_duplicates('Item').set_index('Item')['Category'].to_dict())
item_category_map

In [ ]:
df['Category'] = df.apply(lambda row: item_category_map.get(row['Item'], row['Category']), axis=1)
# qolga 4 ta Category nanlari qatorini o'chirib yuborish
df.drop(df[df['Category'].isna()].index, inplace=True)

#11) Bir xil, lekin turlicha yozilgan qiymatlar (Coffee, cofee, COFEE) mavjudligini tekshiring va tuzating.

In [164]:
#javobni shu yerda yozing
sorted(df['Item'].unique())

['Beef Chili',
 'Brownie',
 'Cheese Fries',
 'Cheesecake',
 'Chicken Melt',
 'Chocolate Cake',
 'Coca Cola',
 'French Fries',
 'Fruit Salad',
 'Garlic Bread',
 'Grilled Chicken',
 'Grilled Vegetables',
 'Ice Cream',
 'Iced Tea',
 'Lemonade',
 'Mashed Potatoes',
 'Nachos Grande',
 'Onion Rings',
 'Orange Juice',
 'Pasta Alfredo',
 'Salmon',
 'Side Salad',
 'Steak',
 'Sweet Potato Fries',
 'Vegetarian Platter',
 'Water']

#12) `Customer ID` yoki boshqa identifikatorlarning takrorlanishini tekshiring.

In [168]:
#javobni shu yerda yozing
df['CustomerID'].duplicated().sum()

np.int64(17430)

#13) Mahsulotning ortiqcha taʼriflarini olib tashlang (Water (0.5), Water (1.0), Water → faqat Water qoldirish).

In [181]:
#javobni shu yerda yozing
# yuqorida bajargan df['Item'] = df["Item"].str.extract("([a-zA-Z\s]+)", expand=False).str.strip().str.title() allaqachon shu vazifani bajargan
df[df['Item'] == "Water"].sample(5)

,OrderID,CustomerID,Category,Item,Price,Quantity,TotalPrice,Date,PaymentMethod
235,ORD_851224,CUST_048,Drinks,Water,1.0,1.0,1.0,2022-04-01,Credit Card
14665,ORD_387937,CUST_029,Drinks,Water,1.0,1.0,1.0,2022-02-10,Credit Card
366,ORD_365262,CUST_013,Drinks,Water,1.0,1.0,1.0,2023-11-13,Digital Wallet
16484,ORD_504532,CUST_089,Drinks,Water,1.0,4.0,4.0,2023-03-24,Cash
4342,ORD_121294,CUST_017,Drinks,Water,2.5,4.0,10.0,2023-03-02,Cash

#**Qayta ishlangan maʼlumotlar bilan tahlil**

#14) Eng koʻp sotilgan 5 ta mahsulotni aniqlang.

In [171]:
#javobni shu yerda yozing
df['Item'].value_counts().head()

Item
Pasta Alfredo    1350
Water            1334
Side Salad       1322
Ice Cream        1295
French Fries     1218
Name: count, dtype: int64

#15) Har bir mijoz oʻrtacha qancha pul sarflaganini hisoblang.

In [175]:
#javobni shu yerda yozing
df.groupby("CustomerID")['TotalPrice'].mean()

CustomerID
CUST_001    17.407303
CUST_002    19.370056
CUST_003    16.604294
CUST_004    18.652299
CUST_005    17.382911
              ...
CUST_096    18.569588
CUST_097    19.358696
CUST_098    19.775000
CUST_099    20.309816
CUST_100    18.322500
Name: TotalPrice, Length: 100, dtype: float64

#16) Mijozlarning qaysi kunlarda koʻproq xarid qilgani bo‘yicha tahlil qiling.

In [182]:
#javobni shu yerda yozing
df['Date'].dt.day_name().value_counts()

Date
Friday       2530
Monday       2526
Saturday     2525
Thursday     2514
Sunday       2482
Wednesday    2477
Tuesday      2476
Name: count, dtype: int64

#17) Narxi oʻrtacha narxdan ikki barobar yuqori boʻlgan mahsulotlarni toping.

In [207]:
#javobni shu yerda yozing
price_avg = df['Price'].mean()
print("price_avg:", round(price_avg))
items_price_avg_x2 = df[df['Price'] > 2 * price_avg]
print("items_price_avg_x2:", items_price_avg_x2['Item'].unique())
items_price_avg_x2[['Item', 'Price']]

price_avg: 6
items_price_avg_x2: ['Grilled Chicken' 'Salmon' 'Pasta Alfredo' 'Vegetarian Platter' 'Steak']

                     Item  Price
2         Grilled Chicken   15.0
5                  Salmon   18.0
7           Pasta Alfredo   15.0
9      Vegetarian Platter   14.0
11                 Salmon   18.0
...                   ...    ...
17453              Salmon   18.0
17480              Salmon   18.0
17490              Salmon   18.0
17495               Steak   20.0
17505       Pasta Alfredo   15.0

[2379 rows x 2 columns]

#18) Mahsulotlar kategoriyalari bo‘yicha tahlil qiling va eng ko‘p sotiladigan kategoriyalarni aniqlang.

In [220]:
#javobni shu yerda yozing
df['Category'].value_counts().head(3)

Category
Main Dishes    3550
Starters       3525
Desserts       3496
Name: count, dtype: int64

In [219]:
# tushum bo'yicha
df.groupby(df['Category'])['TotalPrice'].sum().sort_values(ascending=False)

Category
Main Dishes    160642.0
Starters        60100.0
Desserts        56976.0
Side Dishes     40623.0
Drinks          22678.5
Name: TotalPrice, dtype: float64

In [222]:
df.groupby(df['Category'])['Quantity'].sum().sort_values(ascending=False)

Category
Main Dishes    10638.0
Starters       10429.0
Drinks         10338.0
Desserts       10336.0
Side Dishes    10235.0
Name: Quantity, dtype: float64

#19) Har bir mijozning oʻrtacha xarid miqdorini (`groupby("customer_id")`) hisoblang.

In [224]:
#javobni shu yerda yozing
df.groupby(df['CustomerID']).TotalPrice.mean().head()

CustomerID
CUST_001    17.407303
CUST_002    19.370056
CUST_003    16.604294
CUST_004    18.652299
CUST_005    17.382911
Name: TotalPrice, dtype: float64

#20) Qanday omillar sotuv hajmiga ta’sir qiladi? Bu bo‘yicha umumiy xulosa chiqaring. Javobni quyida kommentariya sifatida yozing!

In [ ]:
#javobni shu yerda yozing

"""
  Umuman olganda, sotuv hajmiga mahsulot narxi, hafta kunlari, to'lov turining qulayligi kabi omillar ta'sir qiladi.
  Eng qimmat - Main Dishes	(20.0) va eng arzon Drinks (3.0) haftaning yakshanba (Sunday) kunida yaxshi sotilyapti.
  Main Dishes sotuvda ham yaxshi ko'rsatkichga ega.

"""

In [254]:
# Kategoriyalar bo‘yicha sotuv hajmi:
df.groupby('Category')['TotalPrice'].sum().sort_values(ascending=False)

Category
Main Dishes    160642.0
Starters        60100.0
Desserts        56976.0
Side Dishes     40623.0
Drinks          22678.5
Name: TotalPrice, dtype: float64

In [227]:
# Hafta kunlari bo‘yicha sotuvlar
df.groupby(df['Date'].dt.day_name())['TotalPrice'].sum().sort_values(ascending=False)

Date
Tuesday      49753.0
Sunday       49663.0
Monday       49358.5
Friday       48721.5
Saturday     48404.5
Thursday     48052.5
Wednesday    47066.5
Name: TotalPrice, dtype: float64

In [238]:
df.groupby('CustomerID')['TotalPrice'].sum().describe()

count     100.000000
mean     3410.195000
std       345.574415
min      2666.000000
25%      3164.875000
50%      3420.750000
75%      3619.375000
max      4116.000000
Name: TotalPrice, dtype: float64

In [239]:
df['Category'].value_counts()

Category
Main Dishes    3550
Starters       3525
Desserts       3496
Drinks         3488
Side Dishes    3471
Name: count, dtype: int64

In [243]:
df.groupby(['Category', df['Date'].dt.day_name()])['TotalPrice'].sum().sort_values(ascending=False)

Category     Date
Main Dishes  Sunday       24535.0
             Tuesday      23923.0
             Monday       23303.0
             Friday       23199.0
             Saturday     22333.0
             Thursday     22084.0
             Wednesday    21265.0
Starters     Thursday      9094.0
             Wednesday     8746.0
             Sunday        8635.0
Desserts     Saturday      8613.0
Starters     Saturday      8611.0
Desserts     Monday        8442.0
Starters     Monday        8429.0
             Tuesday       8425.0
Desserts     Tuesday       8258.0
Starters     Friday        8160.0
Desserts     Sunday        8010.0
             Wednesday     7969.0
             Thursday      7911.0
             Friday        7773.0
Side Dishes  Friday        6296.0
             Monday        6074.0
             Tuesday       5987.0
             Wednesday     5984.0
             Saturday      5667.0
             Thursday      5565.0
             Sunday        5050.0
Drinks       Sunday        3433.0
             Thursday      3398.5
             Friday        3293.5
             Saturday      3180.5
             Tuesday       3160.0
             Monday        3110.5
             Wednesday     3102.5
Name: TotalPrice, dtype: float64

In [245]:
df.groupby('Category')['Price'].sum().sort_values(ascending=False)

Category
Main Dishes    52812.0
Starters       20053.0
Desserts       19030.0
Side Dishes    13647.0
Drinks          7584.5
Name: Price, dtype: float64

In [246]:
df.groupby('Category')['Price'].max()

Category
Desserts        7.0
Drinks          3.0
Main Dishes    20.0
Side Dishes     5.0
Starters       10.0
Name: Price, dtype: float64

In [252]:
df.groupby('Category')['Quantity'].sum().sort_values(ascending=False)

Category
Main Dishes    10638.0
Starters       10429.0
Drinks         10338.0
Desserts       10336.0
Side Dishes    10235.0
Name: Quantity, dtype: float64

In [253]:
df.groupby('PaymentMethod')['Quantity'].sum().sort_values(ascending=False)

PaymentMethod
Credit Card       19476.0
Cash              16455.0
Digital Wallet    16045.0
Name: Quantity, dtype: float64